### ISSUE TITLE
The version on ruby gems has an error…

### ISSUE THREAD

**Issue by alappe** [jordansissel/vagrant-port#1]
I do not know why, but it seems the version on rubygems is missing commit 0103d9e617b83c that fixed the required filename from port to plugin.

Installing via `vagrant plugin install vagrant-port` resulted in the broken version and downloading and unpacking by hand from rubygems too…

**Comment by garethrees** [comment]
FWIW I patched this locally by applying the change to `~/.vagrant.d/gems/gems/vagrant-port-0.0.2/lib/vagrant-port.rb`

**Comment by achingbrain** [comment]
@jordansissel Any chance of releasing a new version with the missing commit?

**Comment by rsrchboy** [comment]
...please!

**Comment by jordansissel** [comment]
Sorry for the delays folks!

Vagrant 1.8 has 'vagrant port' built-in now. Yay! I'll close this in favor of Vagrant 1.8's feature. :)
https://github.com/mitchellh/vagrant/blob/master/CHANGELOG.md#180-december-21-2015
