### ISSUE TITLE
Plugin Load failure

### ISSUE THREAD

**Issue by psychemedia** [jordansissel/vagrant-port#4]
With vagrant 1.6.2 on OS/X 10.9.4 the plugin seems to install okay with `vagrant plugin install vagrant-port`, but when I call it I get an error:

```
$ vagrant port
Vagrant failed to initialize at a very early stage:

The plugins failed to load properly. The error message given is
shown below.

cannot load such file -- vagrant-port/port
```

**Comment by jobevers** [comment]
Same thing happens to me with 1.6.5

I tried to take a look at it, but testing plugins with vagrant seems to be a dark-art that I couldn't figure out.

**Comment by pacuna** [comment]
+1

**Comment by thomaswsdyer** [comment]
Same error - running any vagrant command (using version 1.7.2)

```
$ vagrant status
Vagrant failed to initialize at a very early stage:

The plugins failed to load properly. The error message given is shown below.

cannot load such file -- vagrant-port/port
```

**Comment by garethrees** [comment]
See #1

**Comment by jordansissel** [comment]
Vagrant 1.8 has 'vagrant port' built-in now. Yay! I'll close this in favor of Vagrant 1.8's feature. :)
https://github.com/mitchellh/vagrant/blob/master/CHANGELOG.md#180-december-21-2015
