### ISSUE TITLE
no port command with vagrant 1.7.2

### ISSUE THREAD

**Issue by wstaples** [jordansissel/vagrant-port#5]
after installing vagrant-port plugin typing vagrant port outputs 
`Usage: vagrant [options] <command> [<args>]`
as though it was not a valid command. if I run vagrant list-commands I do not see port listed anywhere. 

I'm using vagrant 1.7.2 on windows 7. 

Here is the plugin list:
vagrant-cachier (1.2.0)
vagrant-port (0.0.2)
vagrant-share (1.1.4, system)

I did alter the vagrant-port.rb as advised here #1 
I changed 
`require "vagrant-port/port"`
to
`require "vagrant-port"`

I have tried uninstalling / reinstalling the plugin with no luck. Any Ideas?

**Comment by jordansissel** [comment]
Not sure what the issue was, sorry for the delay also.

Vagrant 1.8 has 'vagrant port' built-in now. Yay! I'll close this in favor of Vagrant 1.8's feature. :)
https://github.com/mitchellh/vagrant/blob/master/CHANGELOG.md#180-december-21-2015
